steps:
  # Step 1: Install dependencies (gunakan Node.js v20)
  - name: "node:20"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ ! -d "node_modules" ]; then
          echo "node_modules not found, installing dependencies..."
          npm install
        else
          echo "node_modules already exists, skipping npm install"
        fi
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: "/root/.npm"

  # Step 2: Build the frontend
  - name: "node:20"
    entrypoint: "bash"
    args:
      - -c
      - |
        npm run build
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: "/root/.npm"
    
  # Step 3: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: ["app", "deploy", "--quiet"]
    dir: "frontend"

options:
  logging: CLOUD_LOGGING_ONLY
